version: '3.7'

services:
  productkeycheck:
    container_name: productkeycheck
    build: .
    environment:
      - "FLAG=ptm{sample_flag}"
    restart: 'unless-stopped'
    ports:
      - "3232:3232"
    cpus: 2
    mem_limit: 2G
